name: Sync with S3

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install or Update AWS CLI
        run: |
          # Check if AWS CLI is installed and update if necessary
          if ! command -v aws &> /dev/null; then
            echo "AWS CLI not found, installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          else
            echo "AWS CLI already installed, updating..."
            # Run the update using the existing AWS CLI path
            sudo /usr/local/aws-cli/v2/current/bin/aws --update
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Replace with your AWS region

      - name: Sync with S3
        run: |
          aws s3 sync . s3://afrikabucknor.com/ --delete
